# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

references:
  install_global_packages: &install_global_packages
    run: {name: 'Install global packages', command: 'npm install'}

defaults: &defaults
    docker:
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    
jobs:
  pfml-cal-benefits:
    <<: *defaults
    steps:
      - checkout
      - *install_global_packages
      - run:
          name: 'PFML Benefits Calculator Install Packages'
          command: cd PFML/BenefitsCalculator && npm install
      - run:
          name: 'PFML Benefits Calculator Lint'
          command: cd PFML/BenefitsCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Benefits Calculator Build App'
          command: cd PFML/BenefitsCalculator && npm run build
  pfml-cal-contribution:
    <<: *defaults
    steps:
      - checkout
      - *install_global_packages
      - run:
          name: 'PFML Contribution Calculator Install Packages'
          command: cd PFML/ContributionCalculator && npm install
      - run:
          name: 'PFML Contribution Calculator Lint'
          command: cd PFML/ContributionCalculator && npm run build-css && npm run lint
      - run:
          name: 'PFML Contribution Calculator Build App'
          command: cd PFML/ContributionCalculator && npm run build
  ui-cal-benefits:
    <<: *defaults
    steps:
      - checkout
      - *install_global_packages
      - run:
          name: 'UI Benefits Calculator Install Packages'
          command: cd UI/BenefitsCalculator && npm install
      - run:
          name: 'UI Benefits Calculator Lint'
          command: cd UI/BenefitsCalculator && npm run build-css && npm run lint
      - run:
          name: 'UI Benefits Calculator Build App'
          command: cd UI/BenefitsCalculator && npm run build
  ui-cal-part-time-benefits:
    <<: *defaults
    steps:
      - checkout
      - *install_global_packages
      - run:
          name: 'UI Part Time Benefits Calculator Install Packages'
          command: cd UI/PartTimeBenefitsCalculator && npm install
      - run:
          name: 'UI Part Time Benefits Calculator Lint'
          command: cd UI/PartTimeBenefitsCalculator && npm run build-css && npm run lint
      - run:
          name: 'UI Part Time Benefits Calculator Build App'
          command: cd UI/PartTimeBenefitsCalculator && npm run build
workflows:
  version: 2
  test:
    jobs:
      - pfml-cal-benefits
      - pfml-cal-contribution
      - ui-cal-benefits
      - ui-cal-part-time-benefits
