# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  pfml-cal-1:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'PFML Cal One Install Packages'
          command: cd PFML/CalculatorOne && npm install
      - run: 
          name: 'PFML Cal One Lint'
          command: cd PFML/CalculatorOne && npm run build-css && npm run lint
      - run: 
          name: 'PFML Cal One Build App'
          command: cd PFML/CalculatorOne && npm run build
  pfml-cal-3:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: 'PFML Cal Three Install Packages'
          command: cd PFML/CalculatorThree && npm install
      - run: 
          name: 'PFML Cal Three Lint'
          command: cd PFML/CalculatorThree && npm run build-css && npm run lint
      - run: 
          name: 'PFML Cal Three Build App'
          command: cd PFML/CalculatorThree && npm run build
workflows:
  version: 2
  test:
    jobs:
      - pfml-cal-1
      - pfml-cal-3